
GET http://localhost/bikes-per-? HTTP/1.1

###

GET http://localhost/bikes-per-power HTTP/1.1

###

GET http://localhost/bikes-per-brand HTTP/1.1

###

GET http://localhost/bikes-per-city HTTP/1.1

###

GET http://localhost/bikes-per-age HTTP/1.1

###

GET http://localhost/bikes-per-owner HTTP/1.1

###

GET http://localhost/status HTTP/1.1

###

POST http://localhost/post-data HTTP/1.1
Content-Type: application/json

{
    "name": "test",
    "age": 0,
    "city": "example city",
    "brand": "example brand",
    "owner": "example owner",
    "data": "/Used_Bikes.csv"
}

###

POST http://localhost/info HTTP/1.1
Content-type: application/json

{
    "name": "zibetest1",
    "age": 16,
    "sex": "male"
}